spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetchRegistry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
